- README.md
Added more detailed instructions to get started on c9.io, install babel, and compile with babel
> add babel instructions to readme

- docs/docs.css
> add padding to code blocks

- create.html
- src/woof.es6.js
Prompts user to change their variable if they leave default sprite1 and then changes in the code for all instances
> Sprite hint

- dist/woof.js
- docs/index.html
- src/woof.es6.js
fixes #265 
plus, adds flexibility to keysDown.includes() and onKeyDown() by allowing upper/lower case, and more key name possibilities
> make key events more comprehensive and user-friendly

- create.html
when you click the entire bar nothing happens, only minimized on clicking x
> when you click x minimize

- dist/woof.js
- docs/index.html
- src/woof.es6.js
`random()` now returns a number with the same number of decimals as the numbers you put in
closes #332
> make random return same number of decimals

- create.html
- dist/woof.js
- src/woof.es6.js
#338 - reproduced the bug in /create by adding doctype. Added 100% width/height to html and body tags and #project and #backdrop divs which resolved it.
> make backdrop div 100% width/height

- README.md
hey ,this is the same as #348 .But i closed it because of accidently due to force pushing.so i opened a new request.Any problems with that @stevekrouse
> Add cloud9 button

- create.html
> make woofjs/create fill page

- create.html
I noticed after the fact that recent style changes to create.html (#364) were not rendering properly in Safari. These changes should fix it.
> Safari fixes

- create.html
Fixes #369 
I have added tooltips to the buttons on respective iframes.
Kindly review @stevekrouse if they are up to the mark.
> Added tooltips to all iframes

- docs/docs.css
- docs/index.html
Fixed #360 
Let me know what you think @stevekrouse .
> Create New Image button added

- team-full.html
- team.html
- user.html
Basics of simultaneous google-doc style team editing working!! 🎉 
* full screen viewing works
* you can see the team projects you've edited on your /user page
* tells you whether changes are saved or not in top-right corner
* firebase permssions are set so that this works and validates some basic stuff and doesn't let people delete history
Will close #307.
Things to be done:
Once this is merged in, we'll need to:
* try it out with a few select teachers and students
* if it works, publish it more broadly (email to parents, blog post, hacker news)
* make this feature more discoverable
> collaborative editing on /team

- dist/woof.js
- src/woof.es6.js
#221 - 'Lines' drawn as rectangles and rotated. Further tested on Fly Trap game: http://bit.ly/2qg509N
> rectify collision detection on lines

- create.html
Addresses [#403](https://github.com/stevekrouse/WoofJS/issues/403)
Added realtime validation for invalid characters.
Automatically replaces all spaces with dashes.
Displays nice error message if project name is already taken (but this is not in realtime).
> Added better naming dialogue

- docs/index.html
Addresses [#407](https://github.com/stevekrouse/WoofJS/issues/407)
Do you like how it is embedded in an iframe or should we just put a link.
> adding cloning tutorial to docs

- README.md
> Correct minor readme typo

- README.md
> Added some hyperlinks

- create.html
> Migrate Old Users

- create.html
- vendor/levenshtein.js
Addresses #396 - Offers suggestions for misspelled variables and Woof methods using Levenshtein library if distance between words is less than 3.
> add suggestions for misspelled variables and methods

- analytics.html
- create.html
- firebase-migrations.js
Before we merge this in, it probably makes sense to delete the `code-meta-data` table and rerun the migration in the code below.
> Project meta data

- analytics.html
- create.html
- firebase-migrations.js
NOT READY FOR MERGE
Work on this after this pull is merged https://github.com/stevekrouse/WoofJS/pull/481
> fix analytics graph

- docs/index.html
- vendor/codemirror/javascript-hint.js
Addresses first part of PR #521 - adds true to conditional blocks so that an error isn't automatically created.
> remove error from if blocks

- docs/index.html
> Fixes URL for the bossShip2 sprite

- docs/index.html
> remove chuck norris integration.

- README.md
Clarifies the process of setting a username in git, branching from a clean master and staging changes.
Also links the small license image at the top of it to the license.
> Adds several steps to the contribution section of the readme

- docs/index.html
After phone chatting with @stevekrouse I redid the touching text and diagnosed the extra files I was seeing in pull request. I'm not sure why, but "git add ." seemed to cause it. I followed the instructions that showed up in my editor to remove it before committing it. Can do that in the future if it shows up. I'm going to pull request this, and merge it as @stevekrouse instructed. 
Thanks for your help and support @stevekrouse!
~Kate
> Touching text fix 3

- create.html
@stevekrouse This is the more concise version of #559. This can be merged and #559 close. Can probably make it more concise, but not sure that is as necessary as what I already did. Thoughts?
> a more concise version of code fixing the URL error bug

- woof.js
Minor patch for Issues #603 and #606
> Fixing #603 and #606

- create.html
- woof.js
Addressing #605 , where this feels like it addresses the underlying cause so should hopefully resolve it.
> Prevent double-adding of the project

- create.html
- docs/index.html
- woof.js
Updating the Integrations documentation, making the example integrations work and adding more detail for how to include custom integrations/use `getData()`. Closes #587
> Integrations Update

- woof.js
I mistakenly didn't have showing propagate down through bundles, which made it so text couldn't be hidden. Fixing here.
> Fixing hiding/showing for Bundles (and also Text)

- create.html
- woof.js
For text sprites:
- Updated size changes to properly fully propagate down to the TextPrimatives
- Made passing objects to the constructor properly pass relevant information on to the super call to Sprite (i.e. so x, y, angle, etc. would properly register when passed in an object)
For Firefox Compatibility, see more in depth documentation in #633
> Text Updates and Firefox Compatibility

- woof.js
Forgot 'this.' before arguments[0] in Text's super call to Bundle.
> Fixing silly mistake

- create.html
- full.html
- run-code.js
- team-full.html
- team.html
- woof.js
Quick fix to text for #644 .
The larger refactor of `runCode` was somewhat to allow a future project (collecting errors of all saved projects, #567 ) to run smoother, and somewhat to try to address differences between code running on create.html and full.html. I'm having issues replicating the differences between create/full, but still think it's reasonable to have this code as reusable as possible.
> Text Fix + Refactoring runCode into separate file
