create.html
vendor/codemirror/scrollpastend.js

I tried a few things:
1) Added scroll past end plugin
2) Added more blank lines to text editor. I tried 60 lines at one point (is there a better way to do this than add 60 "/n"s?) to achieve the goal you were referring to (I believe) but the vertical scrollbar that appears as a result hijacks some of the text editor's limited space when all tabs are open. I still think additional lines might look good, though, and possibly provide users just an iota more direction, so I left it at 25.
3) Another issue the chat window creates besides leaving users wondering what to do when reaching the bottom is confusion over how to horizontally scroll when the line gets too long. I added line wrapping to eliminate this problem altogether.
4) I made the chat window slightly smaller and justified all the …

adjust text editor and chat window settings

---

dist/woof.js
docs/index.html
src/woof.es6.js

I don't see this as being finished, but I want feedback first.
The way I see it, we can't do `every(random(1, 10), 'seconds', () => {...})` because `random()` will just evaluate to a single number, so we need a way to run `random()` within the function itself.
My idea was to allow the `time` parameter passed to `every()` be an array, so you could do something like this: `every([random, 1, 10], 'seconds', () => {...})`
Also, in order for the action to reoccur at random intervals, we can't use `setInterval()`, because that's for regular intervals. So I think we have to repeatedly generate a random number, then use `setTimeout()` with that number, etc. etc.
adding edit: addresses #175  
Another possibility would be to branch this off into a new function called `everyRandom()` -- then you …

allow every to use random intervals

---

dist/woof.js
src/woof.es6.js

Addresses #395 
@madduccino @stevekrouse can you take a look?
I swapped "width" and "height" for "length" and "thickness", since they seem to be more intuitive when dealing with a line. I'm not crazy about "thickness" but I couldn't think of a better alternative. Any thoughts?
That being said, I actually kept "width" and "height" as properties of a line object because those properties are used for rendering and for the collider. I figured it was better this way than putting more if-statements in the renderer and collider. I simply pointed `line.width` to `line.length` and `line.height` to `line.thickness` with getters, and made the setters return errors.
I still need to edit the comments and update the documentation, but I wanted to test it out here first (cloud9 is being a pain...)

make line angle point toward endpoints

---

dist/woof.js
docs/docs.css
docs/index.html
src/woof.es6.js

Added the simple getData() function to Woof and then gave detailed documentation for use of several APIs.
Added documentation for the following:
- Firebase
- Local Storage
- General Get Requests
- Currency Conversion
- Sunrise/Sunset Data
- Scientific Calculator
- Trivia
- Weather
- Financial Data (currently having CORS issues)
- Quotes (currently having CORS issues)
- Jokes (currently having CORS issues)

Integrations

---

README.md

Fixed #441 
In this PR i have refrained to hyper-linkify any woofjs.com coming in headings as it won't look good from a personal opinion, still let me know if we should linkify the ones present in headers as well.

Add hyperlinks to woofjs.com in readme

---

create.html

I noticed that the project naming had a bug that allowed for spaces in project names. If you copied and pasted a string with several spaces it would only replace the first space. This fixes that issue by using a method that replaces all spaces in the string.

fixed spaces in project names bug

---

docs/index.html

I changed the url for the lilypad sprite from "./docs/images/fly-lilipad.png" to "./docs/images/fly-lilypad.png".
Closes #506

Corrected Misspelling of Lilypad Sprite Url

---

create.html

There is a bug in removing error highlight under certain circumstances. Here's an example:
Error created on line 4:
New code added which creates another error on line 3:
Error on line 3 is fixed which resolves the original error that is now on line 6. As a result, `errorLineNumber` stays at 3 and the highlight on line 6 is not removed.
I resolved this by removing the highlight from ALL lines each time `tryRunningCode` is run.

fix bug in error highlighting

---

docs/index.html

Addresses issue #528. Shrinks the image for BB8 from about 8mb to about 800kb, which still looks fine to my eyes

Smaller bb8 image

---

dist/woof.js
docs/index.html
src/woof.es6.js

This fixes the polygons not being clickable bug referenced in #469. It uses the isPointInPath() method, which, instead of defining the shape by top, bottom, right, and left bounds, determines whether the mouse position is a point in the shape's path. The translateToCenter function does not work when this method is used so adjustments for this are made in that function definition.

Polygon event listener

---

README.md
docs/index.html

For the readme, adds a step in the contributing instructions for staging changes and links the small license image at the top of the page to the license.

Clarify git instructions

---

create.html

@truthgoddess and I worked on this together to make the following adjustments that we think will remove most instances of a this.render error as described in issue #536 :
1. We changed the runCode call in the refresh button to debouncedRunCode. This takes away the ability for a user to run the code over and over again, reducing call stack errors to basically none.
2. Inside the runCode function, we changed the timeout from 10 to 100 to slow down the number of times tryRunningCode() is called.
3. We removed an extraneous (seemingly) runCode call here: https://github.com/stevekrouse/WoofJS/blob/master/create.html#L1510
In the future, we hope to a) find more efficient ways to run Woof in Woof (runs very well in JSBin for instance) and b) create more friendly error messages if a this.render …

render error hotfix

---

create.html

Should close #448 if merged.
@stevekrouse I suspect you might have questions and comments on some things. Happy to go back and apply your suggestions.

add tools menu items, and fix a few shortcuts, first try

---

create.html

In #597 the scheduled autosaves (that occur at :25 and :55 of each hour) did not require the user to be logged in (or a project to exist) to initiate a save. This can result in projects being saved (using up project name-space and server resources) while not being associated with a username, which is not good. I'm not exactly sure what assumptions on the FireBase end this breaks, but I suspect it breaks some of them.
This pull request makes it so we don't schedule autosaves unless the user is logged in. A user that is logged in and working on a never-saved project will still have autosaves prompt them to save (by giving the project a name) at :25 and :55 (autosaving based on time dirty and number of changes won't trigger if the project is unnamed because I think it's too annoying to have …

Fixing Issue with Scheduled Autosave

---

create.html

This deals with #534 , making height, width, and sprites more private than they currently are. They are still technically accessible, but follow the "hiding" convention of _cameraX to signify that they are intended to be private (and make accidental collisions much less likely). I've added in "public" variables to access these concepts, using the "old" names to maintain functionality for "legal" saved Woof code. We now throw errors when these variables are improperly modified (width and height can be set if we're not in fullscreen mode, sprites can never be modified), and reading these public variables should behave the same as before.

Protect internal variables

---

create.html

As codemirror updated to Version 6, their links to old css files broke. This is updating them.

Update codemirror links to point at more permanent css files

---

create.html
docs/index.html
woof.js

Main update is to change documentation to no longer use JSON objects for constructors, as per #620 . (I also added some context to Polygon lengths to close #610 )
Various tweaks:
Image Sprites and Sound Objects now have a .url property that behaves like I'd expect (having a get and set property, and setting will update the corresponding media).
Various rotation style stuff was cleaned up (#617 and #618).
My initial investigations and half-fix for #609 are also in this PR, but the errors from that are only marginally better than what we had before (previously it claimed the error was on line 1, now we don't give a line number).

Documentation Update + Minor Tweaks

---

create.html

This fixes #623 by jerry-rigging a "callback" to beforeunload as a 0 time setTimeout. This should work, since if the user clicks "reload" it navigates away from the page, making it so the hash revert is never carried out. (If the user stays on the page, it should immediately revert back to the old hash, to prevent overwriting the destination project)

Fixes #623 by Reverting Hash Change

---

docs/index.html
woof.js

Multiline Text Support, which involved a bit of a refactor:
- A new type of sprite called a Bundle. I considered exposing this to students in the documentation, but seems fairly persnickety for not a huge benefit, leaving it in the background for now. A super basic demo of bundles is [here](https://hallpell.github.io/create.html#hallpell_bundle-demo). Movement, rotation, mouseUp/Down/Over, touching, and deleting should all work. The main thing that doesn't work is size based stuff (width and height are not defined for generic Bundles), which could exist later but isn't worth the effort at the moment.
- Old Text Sprites are now called TextPrimative, and no longer can receive functions (that will evaluate to text) as their text field. (and shouldn't be used by students)
- As of now, Text …

Text Sprite Updates

---

woof.js

Many of the effects of updating text sprites (text, fontFamily, and size) wouldn't impact the underlying TextPrimatives until after it ran `_render`, which was slightly problematic (I tried to set text and then measure width, which wasn't working and the impetus for this change).
This also implies some issues with Bundles. If we update offsetX, offsetY, or offsetAngle of a component sprite in a Bundle, it won't take effect until we run a _render (at the end of a forever loop).

Make Text Sprite Update Quicker

---

woof.js

Main fixes:
1) Event Handlers were building up, as the handlers added in the call to the super-class of Sprite were inaccessible and unable to be removed when sprites were deleted. We now remove those event handlers when a bundle is created, since the bundle gets its own event handlers.
2) I ran into issues where text sprites were being created before the '#project' (and thus the sprite canvas) were initialized. When the _render code ran, it would break and stop the rest of the user's code from running. This may have only been an issue on my local computer, (it didn't seem to be broken on the live site...) but seems generally beneficial to fix it.
3) Opacity/brightness was not being propagated down to components in bundles.

Assorted Text/Bundle Fixes

---

create.html
docs/index.html
full.html
run-code.js
team-full.html
team.html
woof.js

Updating Babel, partially to no longer target ES2015 (and let it try to figure out a reasonable target based on information it gathers from the browser) and partially so we can parse + insert Infinite Loop Busting code.
The loop busting code resolves #437 .
This means that we don't need to be as afraid of for and while loops - if a student accidentally writes an infinite loop, the loop will break with an error after ~4 seconds. Previously this would cause the page to hang and prevent saving of work, which was very frustrating. It should now be more reasonable. I mention for and while loops in the documentation, but don't have examples of them (I think we should still recommend students use range(0,n).forEach(()=>{}) as opposed to a for loop, but want it be more usable for the advanced …

Infinite Loop Busting and Updating Babel target
